trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Terraform
  displayName: Infrastructure creation
  steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: Terraform Installation
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Az_DevOps'
        backendAzureRmResourceGroupName: 'InvenicsDevOps-rg'
        backendAzureRmStorageAccountName: 'devopsterraform'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'terraform.tfstate'
      displayName: Terraform init
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'
      displayName: Terraform validate
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Az_DevOps'
      displayName: Terrafotm plan
    # - task: TerraformTaskV4@4
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'apply'
    #     environmentServiceNameAzureRM: 'Az_DevOps'
    #   displayName: Terraform Apply
