trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Terraform
  displayName: Infrastructure creation
  steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: Terraform Installation
    
